spring:
  profiles:
    active: ocp
  cloud:
    stream:
      bindings:     
        cargoBookingChannel:
          destination: cargoBookings
          group: cargoBookingsQueue
        cargoRoutingChannel:
          destination: cargoRoutings 
          group: cargoRoutingsQueue
        cargoHandlingChannel2:
          destination: cargoHandlings2
          group: cargoHandlingsQueue2   
          contentType: 'application/json'                                      
  datasource:
    url: "jdbc:mysql://mysql.cargotracker:3306/bookingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    username: bookingmsdb
    password: bookingmsdb
  rabbitmq:
    host: my-release-rabbitmq-headless.cargotracker
    port: 5672
    username: guest
    password: guest
  application:
    name: booking        

server:
  port: 8001
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
      environment: test
